### ISSUE TITLE
line breaks don't work in \title

### ISSUE THREAD

**Issue by AndySchroder** [matze/mtheme#125] opened 2015-08-27 23:52 UTC
In regular beamer, I can have a line break in my title page's title easily with this syntax.

    \title{first line \\ second line}

with mtheme, it doesn't work.

I've come up with a bad workaround

    \title{first line \hspace*{100cm} xxx second line}

Note, for some reason the xxx is required because 3 characters are deleted, so xxx are just some dummy characters. This is problematic though because the xxx shows up in the PDF file's title field.

**Comment by ptheywood** [comment] 2015-08-28 14:20
Using `\newline` rather than `\\` appears to work as intended and would avoid your workaround.

i.e

    \documentclass[]{beamer}
    \usetheme{m}
    \title{first line \newline second line}
    \begin{document}
    \maketitle
    \end{document}

However I do also experience the `\\` issue using the following minimal working example

    \documentclass[]{beamer}
    \usetheme{m}
    \title{first line \\ second line}
    \begin{document}
    \maketitle
    \end{document}

Setting `titleformat=regular` rather than `uppercase` or `lowercase` allows `\\` within the title correctly, so it is related to those values.

    \documentclass[]{beamer}
    \usetheme[titleformat=regular]{m}
    \usetheme{m}
    \title{first line \\ second line}
    \begin{document}
    \maketitle
    \end{document}

**Comment by AndySchroder** [comment] 2015-10-28 07:52
\newline seems to work for me although it would be nice if this problem were resolved because new users are going to waste time figure the workaround out.

**Comment by benjamin-weiss** [comment] 2015-12-04 14:35
@matze Although not completely resolved, I think we should close this too, once #161 is merged.

**Comment by matze** [comment] 2015-12-04 14:38
Indeed :smile:

**Closed by matze** 2015-12-04 14:38 UTC
