### ISSUE TITLE
Color of the section title in "metropolis package"

### ISSUE THREAD

**Issue by likanzhan** [matze/mtheme#136] opened 2015-10-13 14:12 UTC
Hi mthemers,
I’m preparing a presentation with the elegant theme you provided.
But I got a problem here: 
as I need to input some Chinese characters in my presentation, so I used the package “ctex”.

However, once I loaded this package, the color of the section title changes to red.
I’m wondering if there is a way to changed it back to the original color?

Thank you very much.

Sincerely
Likan,

Ps, the following is a simplified script I used in my latex
(I typeset it with “XeLatex")

```latex
\documentclass[10pt]{beamer}
\usetheme{m}
\usepackage{ctex}

\title{MEG}
\date{\today}
\author{Likan Zhan}
\institute{MMMM}

\begin{document}
\maketitle

  \section{Neural signal}
\begin{frame}{EEG}
    你好 (Chinese characters)
  \end{frame}
\end{document}
```

**Comment by benjamin-weiss** [comment] 2015-10-13 14:36
Hello Likan,

please wrap your MWE in in a syntax highlighted markdown block in the future. This makes it easier to read. Here is an example how to do that:

    ```Tex
    \begin{example} ... \end{example}
    ```

For more information on the GitHub Markdown support have a look [here](https://guides.github.com/features/mastering-markdown/).

Unfortunately I cannot reproduce your problem. Here is my output of your MWE.

![demo](https://cloud.githubusercontent.com/assets/9158719/10457387/6fbe8f6e-71c6-11e5-8d0d-72c1b5daef5d.png)

So some followup questions:

* Do you use the most recent version of Metropolis?
* Which TeX-Distribution do you use?
* Are all packages you use up-to-date? (You can produce an output of all used packages in the log file by adding `\listfiles` to the preamble of your tex file)
* Which operating system do you use?

**Comment by likanzhan** [comment] 2015-10-13 15:44
Thank you very much,
* I used the latest version of Metropolis.
*The TeX-Distribution I used is TexPad  (V1.7.16) on Mac (OS X 10.11)
*I am not sure whether or not all the packages are up-to-date 

 (I've attached the list of files it produced).

The problem is when I run the script without the package {ctex}, like:
```Tex
\documentclass[10pt]{beamer}
\usetheme{m}
%\usepackage{ctex}
\title{MEG}
\listfiles
\begin{document}
\maketitle
\section{Neural signal}
\begin{frame}{EEG}
你好 (Chinese characters)
\end{frame}
\end{document}
```
the color of the section tile is normal, but the chinese characters are not correctly presented:
![no chinese character](https://cloud.githubusercontent.com/assets/10531698/10459824/f587c88a-7203-11e5-8efc-8dd319dda84a.png)

When I use the {ctex}package, like:
```Tex
\documentclass[10pt]{beamer}
\usetheme{m}
\usepackage{ctex}
\title{MEG}
\listfiles
\begin{document}
\maketitle
\section{Neural signal}
\begin{frame}{EEG}
你好 (Chinese characters)
\end{frame}
\end{document}
```
the chinese characters are correctly printed, but the color of the section title changes to red
![untitled](https://cloud.githubusercontent.com/assets/10531698/10459714/5db29972-7203-11e5-94f2-a711537741fc.png)

```list of files

*File List*
  beamer.cls    2015/01/05 3.36 A class for typesetting presentations (rcs-revision 8a39122e1f63)
beamerbasercs.sty    2015/03/08 (rcs-revision 368aa9ba9d38)
beamerbasemodes.sty    2013/09/03 (rcs-revision 768f2d98ca64)
beamerbasedecode.sty    2010/05/01 (rcs-revision efa082c6111d)
   ifpdf.sty    2011/01/30 v2.3 Provides the ifpdf switch (HO)
beamerbaseoptions.sty    2013/03/10 (rcs-revision 47431932db0d)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
geometry.sty    2010/09/12 v5.6 Page Geometry
  ifvtex.sty    2010/03/01 v1.5 Detect VTeX and its facilities (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
 pgfcore.sty    2010/04/11 v3.0.0 (rcs-revision 1.7)
graphicx.sty    2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)
graphics.sty    2014/10/28 v1.0p Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    1999/03/16 v1.09 sin cos tan (DPC)
graphics.cfg    2010/04/23 v1.9 graphics configuration of TeX Live
   xetex.def    2015/03/25 v4.04 LaTeX color/graphics driver for XeTeX (TeX Live/RRM/JK)
  pgfsys.sty    2013/11/30 v3.0.0 (rcs-revision 1.47)
  pgfrcs.sty    2013/12/20 v3.0.0 (rcs-revision 1.28)
everyshi.sty    2001/05/15 v3.00 EveryShipout Package (MS)
  pgfrcs.code.tex
  pgfsys.code.tex
pgfsyssoftpath.code.tex    2013/09/09  (rcs-revision 1.9)
pgfsysprotocol.code.tex    2006/10/16  (rcs-revision 1.4)
  xcolor.sty    2007/01/21 v2.11 LaTeX color extensions (UK)
   color.cfg    2007/01/18 v1.5 color configuration of teTeX/TeXLive
 pgfcore.code.tex
 xxcolor.sty    2003/10/24 ver 0.1
atbegshi.sty    2011/10/05 v1.16 At begin shipout hook (HO)
infwarerr.sty    2010/04/08 v1.3 Providing info/warning/error messages (HO)
 ltxcmds.sty    2011/11/09 v1.22 LaTeX kernel commands for general use (HO)
hyperref.sty    2012/11/06 v6.83m Hypertext links for LaTeX
hobsub-hyperref.sty    2012/05/28 v1.13 Bundle oberdiek, subset hyperref (HO)
hobsub-generic.sty    2012/05/28 v1.13 Bundle oberdiek, subset generic (HO)
  hobsub.sty    2012/05/28 v1.13 Construct package bundles (HO)
ifluatex.sty    2010/03/01 v1.3 Provides the ifluatex switch (HO)
 intcalc.sty    2007/09/27 v1.1 Expandable calculations with integers (HO)
etexcmds.sty    2011/02/16 v1.5 Avoid name clashes with e-TeX commands (HO)
kvsetkeys.sty    2012/04/25 v1.16 Key value parser (HO)
kvdefinekeys.sty    2011/04/07 v1.3 Define keys (HO)
pdftexcmds.sty    2011/11/29 v0.20 Utility functions of pdfTeX for LuaTeX (HO)
pdfescape.sty    2011/11/25 v1.13 Implements pdfTeX's escape features (HO)
bigintcalc.sty    2012/04/08 v1.3 Expandable calculations on big integers (HO)
  bitset.sty    2011/01/30 v1.1 Handle bit-vector datatype (HO)
uniquecounter.sty    2011/01/30 v1.2 Provide unlimited unique counter (HO)
letltxmacro.sty    2010/09/02 v1.4 Let assignment for LaTeX macros (HO)
 hopatch.sty    2012/05/28 v1.2 Wrapper for package hooks (HO)
xcolor-patch.sty    2011/01/30 xcolor patch
atveryend.sty    2011/06/30 v1.8 Hooks at the very end of document (HO)
refcount.sty    2011/10/16 v3.4 Data extraction from label references (HO)
 hycolor.sty    2011/01/30 v1.7 Color options for hyperref/bookmark (HO)
 auxhook.sty    2011/03/04 v1.3 Hooks for auxiliary files (HO)
kvoptions.sty    2011/06/30 v3.11 Key value format for package options (HO)
  pd1enc.def    2012/11/06 v6.83m Hyperref: PDFDocEncoding definition (HO)
hyperref.cfg    2002/06/06 v1.2 hyperref configuration of TeXLive
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
  hxetex.def    2012/11/06 v6.83m Hyperref driver for XeTeX
   puenc.def    2012/11/06 v6.83m Hyperref: PDF Unicode definition (HO)
stringenc.sty    2011/12/02 v1.10 Convert strings between diff. encodings (HO)
rerunfilecheck.sty    2011/04/15 v1.7 Rerun checks for auxiliary files (HO)
se-ascii-print.def    2011/12/02 v1.10 stringenc: Printable ASCII characters
beamerbaserequires.sty    2010/05/01  (rcs-revision efa082c6111d)
beamerbasecompatibility.sty    2012/05/01  (rcs-revision 67c48b3b652d)
beamerbasefont.sty    2015/01/05  (rcs-revision b4b4bee242e2)
 amssymb.sty    2013/01/14 v3.01 AMS font symbols
amsfonts.sty    2013/01/14 v3.01 Basic AMSFonts support
sansmathaccent.sty    2013/03/28
filehook.sty    2011/10/12 v0.5d Hooks for input files
beamerbasetranslator.sty    2010/06/11  (rcs-revision 85fd1cc7fc42)
translator.sty    2010/06/12 ver 1.10
translator-language-mappings.tex
beamerbasemisc.sty    2013/09/03  (rcs-revision a55719c41d85)
beamerbasetwoscreens.sty    2010/05/01  (rcs-revision efa082c6111d)
beamerbaseoverlay.sty    2013/12/25  (rcs-revision f6bd5e3805da)
beamerbasetitle.sty    2010/09/21  (rcs-revision f0446ed0b6ae)
beamerbasesection.sty    2013/06/07  (rcs-revision 60b9fe0f342f)
beamerbaseframe.sty    2014/02/20  (rcs-revision 4b8ceeeff434)
beamerbaseverbatim.sty    2015/01/05  (rcs-revision 431510bb5890)
beamerbaseframesize.sty    2011/09/12  (rcs-revision 70f9d8411e54)
beamerbaseframecomponents.sty    2013/10/18  (rcs-revision 5cf6c5555a45)
beamerbasecolor.sty    2015/02/21  (rcs-revision d944b04ee2d5)
beamerbasenotes.sty    2012/12/19  (rcs-revision 1686da3db3c9)
beamerbasetoc.sty    2015/03/08  (rcs-revision 7270298bbaae)
beamerbasetemplates.sty    2010/05/01  (rcs-revision efa082c6111d)
beamerbaseauxtemplates.sty    2014/06/30  (rcs-revision 580088513a67)
beamerbaseboxes.sty    2012/05/13  (rcs-revision 56972908a390)
beamerbaselocalstructure.sty    2014/09/10  (rcs-revision 393f6dcff371)
enumerate.sty    2014/10/28 v3.00 enumerate extensions (DPC)
beamerbasenavigation.sty    2015/02/27  (rcs-revision 923f4bf87efa)
beamerbasetheorems.sty    2010/06/06  (rcs-revision 7e7cc5e53e9d)
 amsmath.sty    2013/01/14 v2.14 AMS math features
 amstext.sty    2000/06/29 v2.01
  amsgen.sty    1999/11/30 v2.0
  amsbsy.sty    1999/11/29 v1.2d
  amsopn.sty    1999/12/14 v2.01 operator names
  amsthm.sty    2015/03/04 v2.20.2
beamerbasethemes.sty    2010/05/01  (rcs-revision efa082c6111d)
beamerthemedefault.sty    2010/06/17  (rcs-revision d02a7cf4d8ae)
beamerfontthemedefault.sty    2012/12/19  (rcs-revision 1686da3db3c9)
beamercolorthemedefault.sty    2012/12/19  (rcs-revision 1686da3db3c9)
beamerinnerthemedefault.sty    2014/06/30  (rcs-revision 580088513a67)
beamerouterthemedefault.sty    2012/12/19  (rcs-revision 1686da3db3c9)
beamerthemem.sty    2015/06/12 Metropolis Beamer theme
etoolbox.sty    2015/05/04 v2.2 e-TeX tools for LaTeX (JAW)
 pgfopts.sty    2014/07/10 v2.1a LaTeX package options with pgfkeys
 pgfkeys.sty    
 pgfkeys.code.tex
beamerinnerthememetropolis.sty    2015/06/12 Metropolis inner theme
    calc.sty    2014/10/28 v4.3 Infix arithmetic (KKT,FJ)
    tikz.sty    2013/12/13 v3.0.0 (rcs-revision 1.142)
     pgf.sty    2013/12/18 v3.0.0 (rcs-revision 1.14)
pgfcomp-version-0-65.sty    2007/07/03 v3.0.0 (rcs-revision 1.7)
pgfcomp-version-1-18.sty    2007/07/23 v3.0.0 (rcs-revision 1.1)
  pgffor.sty    2013/12/13 v3.0.0 (rcs-revision 1.25)
 pgfmath.sty    
 pgfmath.code.tex
  pgffor.code.tex
    tikz.code.tex
beamerouterthememetropolis.sty    2015/06/12 Metropolis outer theme
beamercolorthememetropolis.sty    2015/06/12 Metropolis color theme
beamerfontthememetropolis.sty    2015/06/12 Metropolis font theme
fontspec.sty    2015/03/14 v2.4c Font selection for XeLaTeX and LuaLaTeX
   expl3.sty    2015/03/01 v5547 L3 programming layer (loader) 
expl3-code.tex    2015/03/01 v5547 L3 programming layer 
l3unicode-data.def    2015/03/01 v5544 L3 Unicode data
l3xdvipdfmx.def    
  xparse.sty    2014/11/25 v5471 L3 Experimental document command parser
fontspec-patches.sty    2015/03/14 v2.4c Font selection for XeLaTeX and LuaLaTeX
fontspec-xetex.sty    2015/03/14 v2.4c Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
  eu1enc.def    2010/05/27 v0.1h Experimental Unicode font encodings
  eu1lmr.fd    2009/10/30 v1.6 Font defs for Latin Modern
xunicode.sty    2011/09/09 v0.981 provides access to latin accents and many other characters in Unicode lower plane
 eu1lmss.fd    2009/10/30 v1.6 Font defs for Latin Modern
fontspec.cfg
    ctex.sty    2015/05/16 v2.0.2 Chinese adapter in LaTeX (CTEX)
l3keys2e.sty    2014/11/25 v5471 LaTeX2e option processing using LaTeX3 keys
  fix-cm.sty    2015/01/14 v1.1t fixes to LaTeX
  ts1enc.def    2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
everysel.sty    2011/10/28 v1.2 EverySelectfont Package (MS)
ctexopts.cfg    2015/05/16 v2.0.2 Option configuration file (CTEX)
ctex-engine-xetex.def    2015/05/16 v2.0.2 XeLaTeX adapter (CTEX)
   xeCJK.sty    2015/05/15 v3.3.2 Typesetting CJK scripts with XeLaTeX
xtemplate.sty    2014/11/25 v5471 L3 Experimental prototype document functions
xunicode-addon.sty    2015/05/15 v3.3.2 addon file for xunicode
xunicode.sty    2011/09/09 v0.981 provides access to latin accents and many other characters in Unicode lower plane
xunicode-extra.def    2015/05/15 v3.3.2 extra definition for xunicode
   xeCJK.cfg    2015/05/15 v3.3.2 Configuration file for xeCJK package
xeCJKfntef.sty    2015/05/15 v3.3.2 xeCJK font effect
    ulem.sty    2012/05/18
 environ.sty    2014/05/04 v0.3 A new way to define environments
trimspaces.sty    2009/09/17 v1.1 Trim spaces around a token list
CJKfntef.sty    2015/04/18 4.8.4
zhnumber.sty    2014/09/13 v2.1 Typesetting numbers with Chinese glyphs
zhnumber-utf8.cfg    2014/09/13 v2.1 Chinese numerals with UTF8 encoding
ctex-scheme-chinese.def    2015/05/16 v2.0.2 Chinese scheme for generic (CTEX)
ctex-name-utf8.cfg    2015/05/16 v2.0.2 Caption with encoding UTF8 (CTEX)
ctex-fontset-fandol.def    2015/05/16 v2.0.2 Fandol fonts definition (CTEX)
    ctex.cfg    2015/05/16 v2.0.2 Configuration file (CTEX)
   t3cmr.fd    2001/12/31 TIPA font definitions
 nameref.sty    2012/10/27 v2.43 Cross-referencing by name of section
gettitlestring.sty    2010/12/03 v1.4 Cleanup title references (HO)
Untitled.out
Untitled.out
translator-basic-dictionary-English.dict    
translator-bibliography-dictionary-English.dict    
translator-environment-dictionary-English.dict    
translator-months-dictionary-English.dict    
translator-numbers-dictionary-English.dict    
translator-theorem-dictionary-English.dict    
    umsa.fd    2013/01/14 v3.01 AMS symbols A
    umsb.fd    2013/01/14 v3.01 AMS symbols B

```

**Comment by benjamin-weiss** [comment] 2015-10-13 16:07
I haven't checked all packages, but at least the `ctex` package is not up-to-date. You have version 2.0.2 installed and the most recent version is 2.2. So just start the `TeX Live Utility`, which should be installed on your system, and update all packages (`Actions > Update All Packages`) or at least the `ctex` package.

FYI: The TeX distribution you use is MacTeX and TexPad is just the LaTeX editor you use.

**Comment by likanzhan** [comment] 2015-10-14 09:08
Thank you very much Benjamin,
I've updated all the packages as you suggested.
And it works. 
Thank you very much.

Likan

**Comment by benjamin-weiss** [comment] 2015-10-14 10:03
You are welcome!

Please close the issue to indicate that your problem is solved.

**Closed** 2015-10-14 10:05 UTC
