### ISSUE TITLE
Make theme compatible with stock color themes

### ISSUE THREAD

**Issue by matze** [matze/mtheme#8] opened 2014-11-12 15:24 UTC
Especially the background is not set correctly.

**Comment by rchurchley** [comment] 2015-06-13 00:27
I have tested cc24402 with the default beamer colour themes: `albatross`, `beaver`, `beetle`, `crane`, `default`, `dolphin`, `dove`, `fly`, `lily`, `orchid`, `rose`, `seagull`, `seahorse`, `sidebartab`, `structure`, `whale`, and `wolverine`. It works essentially as expected, with the following quirks:

- Several themes do not define some colours, expecting to inherit them from `default`; for example, they may intend to have red `alerted text` as per the default but do not specify this. When used with our theme, these styles will fall back to `mtheme`'s colours instead of the defaults. We may want to provide some option for `beamercolorthememetropolis` to *not* set the base colours `normal text`, `alerted text`, and `example text` to allow users to let users revert to the default colour scheme.
- The `\plain{...}` command does not work with the `fly` theme. This is because `fly` has an annoying definition of `palette primary` which specifically *unsets* the background. I don't think there's a non-hacky way of fixing this while maintaining the expected behaviour for the other themes.

**Comment by benjamin-weiss** [comment] 2015-06-13 02:47
> I have tested cc24402 with the default beamer colour themes.

Wow. Sounds like a lot of boring work.

> We may want to provide some option for `beamercolorthememetropolis`

Maybe even go a step further and provide an option not to load the color theme at all. And instead only define the new beamer colors we use?

    \if@nocolortheme
      \setbeamercolor{title separator}{use=progress bar, parent=progress bar}
      \setbeamercolor{progress bar}{%
        use=alerted text,
        fg=alerted text.fg,
        bg=normal text.bg!50!fg
      }
    \else
      \usecolortheme{metropolis}
    \fi

If I get it right, this should also fix the problem and an option like this should be easier to understand than `notSetBaseColors`.

> The `\plain{...}` command does not work with the `fly` theme.

It appears to me that this is a bug of the `fly` theme. I wouldn't really care about that. Lets just keep it in mind and add it to the documentation as a known issue.

**Comment by rchurchley** [comment] 2015-07-09 17:05
> Maybe even go a step further and provide an option not to load the color theme at all. And instead only define the new beamer colors we use?

After splitting the theme into its inner, outer, font, and colour components, it is now possible to take advantage of the structural parts of the theme without loading the colour theme. However, Beamer colors for (e.g.) `progress bar` are not defined if the color theme is not loaded. Should we provide defaults in the inner and outer themes?

**Comment by benjamin-weiss** [comment] 2015-07-09 17:32
We should provide defaults, but I don't think the inner and outer themes are the right place for it. Actually we already provide sensible defaults, as our color definitions of the `progress bar` are dependent on the `alerted text` and the `normal text` color. So if someone just loads the `mtheme` and then a stock color theme, this should work just fine.

So I don't think there is really a need to provide an option to not load the color theme and we can just close this issue.

**Comment by rchurchley** [comment] 2015-07-09 18:05
That's fine by me.

**Closed** 2015-07-10 06:03 UTC
Labels: enhancement
